// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClZHGnD25wrRMPJz5U4asiC7GrAHysKl4',
    appId: '1:749012012796:web:5cb14eb67a84d4fb4a1179',
    messagingSenderId: '749012012796',
    projectId: 'blackcoffer-e1db1',
    authDomain: 'blackcoffer-e1db1.firebaseapp.com',
    storageBucket: 'blackcoffer-e1db1.appspot.com',
    measurementId: 'G-C937NYEKF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAOJL34jDeXtnSnGo-adImtVO-j770Vu4',
    appId: '1:749012012796:android:4e543d25dc5c41a54a1179',
    messagingSenderId: '749012012796',
    projectId: 'blackcoffer-e1db1',
    storageBucket: 'blackcoffer-e1db1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQdB1SreTfZs1gXBiGecrn2Q_MrIZSta0',
    appId: '1:749012012796:ios:2599cbd30ae0092e4a1179',
    messagingSenderId: '749012012796',
    projectId: 'blackcoffer-e1db1',
    storageBucket: 'blackcoffer-e1db1.appspot.com',
    iosBundleId: 'com.example.blackCoffer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQdB1SreTfZs1gXBiGecrn2Q_MrIZSta0',
    appId: '1:749012012796:ios:094ba659b5ff88fa4a1179',
    messagingSenderId: '749012012796',
    projectId: 'blackcoffer-e1db1',
    storageBucket: 'blackcoffer-e1db1.appspot.com',
    iosBundleId: 'com.example.blackCoffer.RunnerTests',
  );
}
